"""Central project settings."""

from .paths import (
    DATA_DIR,
    RESTAURANTS_CSV,
    BUILDINGS_CSV,
    LANDUSE_CSV,
    STREAMLIT_APP,
)
from .pipeline import (
    DEFAULT_CORRIDOR_SIM_HOUR,
    DEFAULT_MIN_DEMAND_WEIGHT,
    DEFAULT_MIN_TIME_DELTA_S,
    DEFAULT_PRUNED_CORRIDOR_COUNT,
    DEFAULT_SIMULATION_CORRIDOR_COUNT,
    DEFAULT_DEMAND_SCALE,
    NETWORK_PEAK_ORDERS_PER_HOUR,
)
from .service import (
    APPROACH_S,
    UNLOAD_S,
    BATTERY_SWAP_S,
    LOAD_NEXT_S,
    AUTOMATED_BATTERY_SWAP_S,
    CV_SQUARED,
    AUTOMATED_CV_SQUARED,
)
from .simulation import (
    TIME_MULTIPLIER,
    TICK_REAL_S,
    SIM_START_S,
    SIM_DURATION_S,
    MAP_CENTER_LAT,
    MAP_CENTER_LON,
    MAP_ZOOM,
    MAP_PITCH,
    MAP_BEARING,
    MAP_STYLE,
    CRUISE_SPEED_MS,
    CLIMB_SPEED_MS,
    DESCENT_SPEED_MS,
    ASSUMED_ALTITUDE_M,
    DEFAULT_FLEET_SIZE,
    RL_FLEET_SIZES,
    COLOR_IDLE,
    COLOR_TAKEOFF,
    COLOR_CRUISE,
    COLOR_LANDING,
    COLOR_COOLDOWN,
    COLOR_CRANING,
    COLOR_HUB_HEAVY,
    COLOR_HUB_MODERATE,
    COLOR_HUB_LIGHT,
    COLOR_CORRIDOR_ARC,
    COLOR_PAD_BUSY,
    COLOR_PAD_FREE,
)

